spring.application.name=supportflow

# JWT
jwt.secret=K9mP2vX7qL4nRw8YcJ5tHs3ZdF6aNb1QeG0uMiVr
jwt.expiration-ms=86400000

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/supportflow
spring.datasource.username=postgres
spring.datasource.password=SupportFlow2026!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Codigo de invitación
app.codigo-invitacion-agente=SUPPORTFLOW2026